### ISSUE TITLE
Can I include this site to Lume showcase?

### ISSUE THREAD

**Issue by oscarotero** [DS4SD/DS4SD.github.io#22]
Hi. I'm the creator of Lume, the static site generator used to build this site.

I was searching on GitHub new projects built with Lume and found this great repository. I'd like to include it in the showcase section of Lume (https://lume.land/showcase/). Are you ok with that?

Thanks for your time.
Óscar.

**Comment by kdinkla** [comment]
Hi Óscar,

Of course, we are more than okay with it. Lume is a joy to use, many thanks for putting it together.

Regards,
Kasper
